
package wse.locadora;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternoCarroWS", targetNamespace = "http://service.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternoCarroWS {


    /**
     * 
     * @param data
     * @return
     *     returns java.util.List<wse.locadora.Reserva>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pesquisarReserva", targetNamespace = "http://service.pos.com/", className = "wse.locadora.PesquisarReservaPorData")
    @ResponseWrapper(localName = "pesquisarReservaResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.PesquisarReservaPorDataResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/pesquisarReservaRequest", output = "http://service.pos.com/ExternoCarroWS/pesquisarReservaResponse")
    public List<Reserva> pesquisarReserva(
        @WebParam(name = "data", targetNamespace = "")
        XMLGregorianCalendar data);

    /**
     * 
     * @param locadoraId
     * @return
     *     returns java.util.List<wse.locadora.Carro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCarrosPorLocadora", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarCarrosPorLocadora")
    @ResponseWrapper(localName = "listarCarrosPorLocadoraResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarCarrosPorLocadoraResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/listarCarrosPorLocadoraRequest", output = "http://service.pos.com/ExternoCarroWS/listarCarrosPorLocadoraResponse")
    public List<Carro> listarCarrosPorLocadora(
        @WebParam(name = "locadoraId", targetNamespace = "")
        Locadora locadoraId);

    /**
     * 
     * @param cidade
     * @return
     *     returns java.util.List<wse.locadora.Locadora>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarLocadorasPorCidade", targetNamespace = "http://service.pos.com/", className = "wse.locadora.BuscarLocadorasPorCidade")
    @ResponseWrapper(localName = "buscarLocadorasPorCidadeResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.BuscarLocadorasPorCidadeResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/buscarLocadorasPorCidadeRequest", output = "http://service.pos.com/ExternoCarroWS/buscarLocadorasPorCidadeResponse")
    public List<Locadora> buscarLocadorasPorCidade(
        @WebParam(name = "cidade", targetNamespace = "")
        String cidade);

    /**
     * 
     * @param reserva
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarReserva", targetNamespace = "http://service.pos.com/", className = "wse.locadora.CriarReserva")
    @ResponseWrapper(localName = "criarReservaResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.CriarReservaResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/criarReservaRequest", output = "http://service.pos.com/ExternoCarroWS/criarReservaResponse")
    public boolean criarReserva(
        @WebParam(name = "reserva", targetNamespace = "")
        Reserva reserva);

    /**
     * 
     * @return
     *     returns java.util.List<wse.locadora.Reserva>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarReservas", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarReservas")
    @ResponseWrapper(localName = "listarReservasResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarReservasResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/listarReservasRequest", output = "http://service.pos.com/ExternoCarroWS/listarReservasResponse")
    public List<Reserva> listarReservas();

    /**
     * 
     * @return
     *     returns java.util.List<wse.locadora.Carro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCarros", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarCarros")
    @ResponseWrapper(localName = "listarCarrosResponse", targetNamespace = "http://service.pos.com/", className = "wse.locadora.ListarCarrosResponse")
    @Action(input = "http://service.pos.com/ExternoCarroWS/listarCarrosRequest", output = "http://service.pos.com/ExternoCarroWS/listarCarrosResponse")
    public List<Carro> listarCarros();

}
